#!/bin/bash
PYTHONPATH=$OPENSHIFT_REPO_DIR/.. $OPENSHIFT_DATA_DIR/bin/python3.3 -m repo.database &
PYTHONPATH=$OPENSHIFT_REPO_DIR/.. $OPENSHIFT_DATA_DIR/bin/gunicorn -D -p $OPENSHIFT_TMP_DIR/gunicorn.pid -w 4 -b 127.0.0.1:8080 repo.core:app
echo %1 > $OPENSHIFT_TMP_DIR/yoboard.database.pid
