#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
if [ -f "$OPENSHIFT_TMP_DIR/yoboard.database.pid" ]
then
    kill $(cat $OPENSHIFT_TMP_DIR/yoboard.database.pid) >/dev/null 2>&1
    kill $(cat $OPENSHIFT_TMP_DIR/gunicorn.pid) >/dev/null 2>&1
    rm $OPENSHIFT_TMP_DIR/yoboard.database.pid
else
    client_result "Application is already stopped"
fi
