#!/bin/bash
killps() {
  kill `ps -ef | grep $1 | grep -v grep | awk '{ print $2 }'`
}

killps 'repo.database'                      >/dev/null 2>&1
killps 'nginx: master process'              >/dev/null 2>&1
kill $(cat $OPENSHIFT_TMP_DIR/gunicorn.pid) >/dev/null 2>&1

